# Generated by Django 4.0.4 on 2022-05-19 06:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lists', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='item',
            name='text',
            field=models.CharField(default='', max_length=250),
            preserve_default=False,
        ),
    ]
